apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-convert
  labels:
    app: convert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convert
  template:
    metadata:
      labels:
        app: convert
    spec:
      containers:
        - name: convert
          image: 192.168.199.128:8000/convert:v1
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: nfs-volume
              mountPath: /streamer/library
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: svc-convert
spec:
  type: NodePort
  selector:
    app: convert
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30003