apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-stream
  labels:
    app: stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      labels:
        app: stream
    spec:
      containers:
        - name: stream
          image: 192.168.199.128:8000/stream:v1
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: nfs-volume
              mountPath: /streamer/api/library
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: svc-stream
spec:
  type: NodePort
  selector:
    app: stream
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001