apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-upload
  labels:
    app: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: upload
          image: 192.168.92.128:8000/upload:v1
          env:
            - name: dbpoint
              value: svc-db.default.svc.cluster.local:3004
            - name: endpoint
              value: svc-convert.default.svc.cluster.local:5000
          ports:
            - containerPort: 3002
          volumeMounts:
            - name: nfs-volume
              mountPath: /streamer/library
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: svc-upload
spec:
  type: NodePort
  selector:
    app: upload
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002
